services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/stressedout
      - SECRET_KEY_BASE=tNbgJQPPiDdvL1R4ed3jy3weVpqwDipPHVL5WWH+aPL3FQ+u/f0H42zjVt1Ll0LZ
      - PHX_HOST=localhost
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stressedout

    volumes:
      - ex_postgres_data:/var/lib/postgresql/data

volumes:
  ex_postgres_data:
